name: WaniKani Review Check

on:
  schedule:
    - cron: "*/8 * * * *"
  workflow_dispatch:

jobs:
  check-reviews:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out code
        uses: actions/checkout@v4
      
      - name: Make script executable
        run: chmod +x ./check.sh
      
      - name: Run WaniKani Check Script
        run: ./check.sh
        
        env:
          WANIKANI_API_TOKEN: ${{ secrets.WANIKANI_API_TOKEN }}-
          MAILJET_API_KEY: ${{ secrets.MAILJET_API_KEY }}
          MAILJET_SECRET_KEY: ${{ secrets.MAILJET_SECRET_KEY }}
          
          MY_EMAIL: ${{ vars.MY_EMAIL }}
          FROM_EMAIL: ${{ vars.FROM_EMAIL }}
